### ISSUE TITLE
return vector even if warning

### ISSUE THREAD

**Issue by SamGG** [cafletezbrant/flowClean#1]
Hi,
When there are too few cells or no time parameter, a flow frame is return even if a returnVector is TRUE.
Could you check the pull request I submit to my fork?
https://github.com/SamGG/flowClean/pull/1
https://github.com/SamGG/flowClean/commit/72349cf63d5f8e7b8bec492c965ff3d8f115cef3
Best.

**Comment by cafletezbrant** [comment]
Sorry for taking so long here ... I just finished grad school, moved across my country and started a new job... Your changes look good. Can you submit PR to my GitHub so I can include before next version of BioC?

**Comment by SamGG** [comment]
I think you already merge my PR. Could you check? Thanks for your feedback.

**Comment by cafletezbrant** [comment]
It doesn't seem that is the case ... I think you forked the repo but then didn't submit a PR to me.

Thanks!

**Comment by SamGG** [comment]
I merged my PR into my fork ;-)
