### ISSUE TITLE
Error in if (!is.na(shifts)) { : the condition has length > 1

### ISSUE THREAD

**Issue by phauchamps** [cafletezbrant/flowClean#5]
Hi @cafletezbrant, 

I recently encountered an error message when trying to run flowClean::clean() on a public dataset. 
The error message was : _Error in if (!is.na(shifts)) { : the condition has length > 1_
 
I found out that this error was due to an if statement in _flowClean:::fix.weird()_, while _shifts_ was of dimension > 1
 
_if (!is.na()(shifts))_
 
On a local copy of this function, I replaced this statement by the following : 
 
_if (length(shifts[!is.na(shifts)]) > 0)_
 
And this seems to solve my error.
 
How can I best proceed with this probable bug fix ? 
Do you want me to raise a pull request on flowClean repo ?

Thanks,

Philippe

**Comment by phauchamps** [comment]
It seems that testing within a if() statement and providing a vector is now (R version 4.2) raising an error while it was only raising a warning before. 
I corrected the bug in created pull request #6

**Comment by cafletezbrant** [comment]
Thanks for this detective work! And yes, R 4.2 is going to surprise many people with this change. I'll review the request later today (looks good based on a skim).

**Comment by cafletezbrant** [comment]
merged pr
