### ISSUE TITLE
Need to push to Bioconductor

### ISSUE THREAD

**Issue by lgatto** [cafletezbrant/flowClean#8]
The package is completely out of sync with Bioconductor and the most recent updates and bug fixes are missing from the official/latest versions on Bioconductor. Could you you please update your package on Bioconductor, ideally in release and devel.

**Comment by cafletezbrant** [comment]
Acknowledging that I've seen both this and upcoming Bioc deadline

**Comment by cafletezbrant** [comment]
Have pushed, should be visible tomorrow.
